<?php

function elis_consumer_get_xml_data_from_url($url) {
  $response = drupal_http_request($url, array('headers' => array('Accept' => 'application/xml')));
  if ($response->code != 200) {
    if (function_exists('drush_log')) {
      drush_log('Could not retrieve data from url: ' . $url, 'error');
    }
    return NULL;
  }
  $data = trim(utf8_encode($response->data));
  try {
    $xml = simplexml_load_string($data);
    return $xml;
  }
  catch (Exception $e) {
    if (function_exists('drush_log')) {
      drush_log('Could not parse the xml from url: ' . $url, 'error');
    }
    return NULL;
  }
}